apiVersion: v1
kind: Namespace
metadata:
  name: code-server
---
apiVersion: v1
kind: Service
metadata:
 name: code-server
 namespace: code-server
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: rushyrush/code-server:latest
        imagePullPolicy: Always
        name: code-server
        volumeMounts:
          - name: code-server-storage
            mountPath: "/home/coder"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Denver         
        - name: PROXY_DOMAIN
          value: code.yourdomain.com                 
        - name: HASHED_PASSWORD
          value: "" 
      volumes:
      - name: code-server-storage
        persistentVolumeClaim:
          claimName: code-server      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server
  namespace: code-server
  labels:
    app: code-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi